dist: xenial
sudo: required
language: python
python:
 - '3.5'

install:
 - pip install tox
 - sudo add-apt-repository -y ppa:juju/stable
 - sudo apt-get update
 - sudo apt-get install -y charm-tools

script:
 - make all
