#!/usr/bin/env python3
import amulet
import unittest


class TestDeployment(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.deployment = amulet.Deployment(series='xenial')

        cls.deployment.add("jenkins", 'cs:~kos.tsakalozos/jenkins')
        cls.deployment.add('cwr','cs:~juju-solutions/cwr')
        cls.deployment.relate('jenkins:extension', 'cwr:jenkins')

        try:
            cls.deployment.setup(timeout=1800)
            cls.deployment.sentry.wait()
            cls.cwr = cls.deployment.sentry['cwr'][0]
        except amulet.helpers.TimeoutError:
            amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
        except:
            raise

    def test_status(self):
        self.deployment.sentry.wait_for_messages(
            {'cwr': 'waiting for controller registration'}, timeout=120)


if __name__ == '__main__':
    unittest.main()
