#!/usr/bin/env python3

import sys

sys.path.append('lib')
from charms.layer.basic import activate_venv  # noqa: E402
activate_venv()

from charmhelpers.core import hookenv  # noqa: E402
from charms.reactive import RelationBase  # noqa: E402
from jenkins import Jenkins  # noqa: E402


def add_job():
    '''
    Adds a job to be triggered when a release on github is marked

    '''
    jenkins_relation = (RelationBase.from_state('jenkins.available'))
    jenkins_connection_info = jenkins_relation.get_connection_info()
    jclient = Jenkins(jenkins_connection_info["jenkins_url"],
                      jenkins_connection_info["admin_username"],
                      jenkins_connection_info["admin_password"])

    charm_name = hookenv.action_get("charm-name")
    refspec = "<refspec>+refs/tags/*:refs/remotes/origin/tags/*</refspec>"

    rep = {"{{gitrepo}}": hookenv.action_get("repo"),
           "{{pushtochannel}}": hookenv.action_get("push-to-channel"),
           "{{lpid}}": hookenv.action_get("lp-id"),
           "{{branch}}": "*/tags/*",
           "{{charmname}}": charm_name,
           "{{refspec}}": refspec,
           "{{controller}}": hookenv.action_get("controller")}

    template_path_source = "templates/BuildMyCharm/config.xml"
    with open(template_path_source) as infile:
        data = infile.read()
        for src, target in rep.items():
            data = data.replace(src, target)
        jclient.create_job("release-charm-{}".format(charm_name), data)


if __name__ == "__main__":
    add_job()
