#!/usr/bin/env python3

import sys

sys.path.append('lib')
from charms.layer.basic import activate_venv  # noqa: E402
activate_venv()

from charmhelpers.core import hookenv  # noqa: E402
from charms.reactive import RelationBase  # noqa: E402
from cwrhelpers import app_from_bundle, fail_action  # noqa: E402
from jenkins import Jenkins  # noqa: E402


def add_job():
    '''
    Adds a job to be triggered upon a commit on github

    '''
    jenkins_relation = (RelationBase.from_state('jenkins.available'))
    jenkins_connection_info = jenkins_relation.get_connection_info()
    jclient = Jenkins(jenkins_connection_info["jenkins_url"],
                      jenkins_connection_info["admin_username"],
                      jenkins_connection_info["admin_password"])

    # If we have a reference bundle, determine the app name used for our charm
    charm_name = hookenv.action_get("charm-name")
    if hookenv.action_get("reference-bundle"):
        bundle_name = hookenv.action_get("reference-bundle")
        if not bundle_name.startswith("cs:"):
            bundle_name = "cs:{}".format(bundle_name)
        bundle_app_name = app_from_bundle(bundle_name, charm_name)

        if not bundle_app_name:
            fail_action("{} not found in {}".format(charm_name, bundle_name))

    rep = {"{{gitrepo}}": hookenv.action_get("repo"),
           "{{pushtochannel}}": hookenv.action_get("push-to-channel") or "",
           "{{lpid}}": hookenv.action_get("lp-id") or "",
           "{{branch}}": hookenv.action_get("branch"),
           "{{charmname}}": charm_name,
           "{{referencebundle}}": bundle_name or "",
           "{{bundleappname}}": bundle_app_name or "",
           "{{refspec}}": "",
           "{{controller}}": hookenv.action_get("controller")}

    template_path_source = "templates/BuildMyCharm/config.xml"
    with open(template_path_source) as infile:
        data = infile.read()
        for src, target in rep.items():
            data = data.replace(src, target)
        jclient.create_job("charm-{}".format(hookenv.action_get("charm-name")), data)


if __name__ == "__main__":
    add_job()
