#!/usr/bin/env python3

from os import getcwd
import sys
sys.path.append('lib')

from charms.layer.basic import activate_venv  # noqa: E402
activate_venv()

from charmhelpers.core import hookenv  # noqa: E402
import cwrhelpers  # noqa: E402


def add_job():
    """Adds a job to be triggered when a PR is submitted."""

    jclient = cwrhelpers.make_jenkins_client()
    charm_name, charm_fname = cwrhelpers.get_charm_names()
    bundle_name, bundle_fname, bundle_app_name = (cwrhelpers.
                                                  get_reference_bundle())

    job_name = "cwr_charm_pr_{}_in_{}".format(charm_fname, bundle_fname)
    context = cwrhelpers.get_common_context(
        job_name, charm_name, bundle_name, bundle_app_name)
    context['charm_home'] = getcwd()
    context['oauth'] = hookenv.action_get("oauth-token")
    token = cwrhelpers.create_jenkins_job(
        jenkins_client=jclient, source="BuildMyPR/config.xml",
        context=context, job_name=job_name)
    url, _ = cwrhelpers.get_info_urls('pr-trigger', token, job_name)
    hookenv.action_set({'hook.url': url})


if __name__ == "__main__":
    add_job()
