#!/usr/bin/env python3

import json
import sys

sys.path.append('lib')
from charms.layer.basic import activate_venv  # noqa: E402
activate_venv()

from charmhelpers.core import hookenv  # noqa: E402
from utils import get_controllers  # noqa: E402


def list_controllers():
    '''
    List controllers by looking at the controller.names file

    Returns: The human friendly names of the registered controllers
    '''
    controllers = get_controllers()
    hookenv.action_set({"results": json.dumps(controllers)})
    hookenv.action_set({'outcome': 'success'})


if __name__ == "__main__":
    list_controllers()
