#!/usr/bin/env python3
import json
from charmhelpers.core import hookenv
from controller.helpers import get_controllers


def list_controllers():
    '''
    List controllers by looking at the controller.names file

    Returns: The human friendly names of the registered controllers
    '''
    controllers = get_controllers()
    hookenv.action_set({"results": json.dumps(controllers)})
    hookenv.action_set({'outcome': 'success'})


if __name__ == "__main__":
    list_controllers()
