#!/usr/bin/env python3
import os
import json
from charmhelpers.core import hookenv

HOME = "/var/lib/jenkins"

def list_controllers():
    '''
    List controllers by looking at the controller.names file

    Returns: The human friendly names of the registered controllers
    '''

    controllers_file_path = "{}/controller.names".format(HOME)
    controllers = []
    if os.path.exists(controllers_file_path):
        controllers = [line.rstrip('\n') for line in open(controllers_file_path)]
    hookenv.action_set({"results": json.dumps(controllers)})
    hookenv.action_set({'outcome': 'success'})


if __name__ == "__main__":
    list_controllers()
