#!/bin/bash

cleanup() {
    rm -f credentials.yaml
    rm -f credentials.base64
}

set_creds() {
    cloud=$(action-get 'cloud')
    action-get 'credentials' | sed 's/ /\n/g' > credentials.base64
    cat credentials.base64 | base64 -d > credentials.yaml
    trap cleanup EXIT
    sudo -u jenkins -- juju add-credential "$cloud" --replace -f credentials.yaml
}

output="$(set_creds 2>&1)"
if [[ $? != 0 ]]; then
    action-fail "$output"
else
    action-set message="$output"
fi
