#!/bin/bash

cleanup() {
    rm -f credentials.yaml
}

set_creds() {
    cloud=$(action-get 'cloud')
    action-get 'credentials' | base64 -d > credentials.yaml
    trap cleanup EXIT

    sudo -u jenkins -- juju add-credential "$cloud" --replace -f credentials.yaml
}

output="$(set_creds 2>&1)"
if [[ $? != 0 ]]; then
    action-fail "$output"
else
    action-set message="$output"
fi
