#!/usr/bin/env python3

import subprocess
import sys
sys.path.append('lib')
from utils import report_status


USER = "jenkins"


def charmstore_logout():
    """
    Logout from the charmstore.
    """
    cmd = ['su', USER, '-c', 'charm logout']
    if subprocess.call(cmd) != 0:
        raise Exception
    report_status()


if __name__ == "__main__":
    charmstore_logout()
