#!/usr/bin/env python3

import subprocess

USER = "jenkins"


def charmstore_logout():
    """
    Logout from the charmstore.
    """
    cmd = ['su', USER, '-c', 'charm logout']
    if subprocess.call(cmd) != 0:
        raise Exception

    subprocess.call(["hooks/update-status"])


if __name__ == "__main__":
    charmstore_logout()
