#!/usr/bin/env python3
from jenkinshelpers import wait_result
from charmhelpers.core import hookenv
from charms.reactive import RelationBase
from jenkins import Jenkins


def unregister_controller():
    '''
    Register a controller. A call to the Jenkins interface is performed
    to trigger the UnregisterController job. This job will wait for one minute
    for the job to complete.
    '''
    jenkins_relation = (RelationBase.from_state('jenkins.available'))
    jenkins_connection_info = jenkins_relation.get_connection_info()
    jclient = Jenkins(jenkins_connection_info["jenkins_url"],
                      jenkins_connection_info["admin_username"],
                      jenkins_connection_info["admin_password"])

    name = hookenv.action_get("name")

    next_build_number = jclient.get_job_info("UnregisterController")['nextBuildNumber']
    params = {'CONTROLLER_NAME': name}
    jclient.build_job("UnregisterController",  params)

    build_outcome, build_output =  wait_result(jclient, "UnregisterController", next_build_number)
    hookenv.action_set({'outcome': build_outcome})
    hookenv.action_set({"output": build_output})


if __name__ == "__main__":
    unregister_controller()
